package fr.laucoin.registry.backend.domain.constant

object ErrorConst {
	const val NOT_IMPLEMENTED_YET = "NOT_IMPLEMENTED_YET"
	const val NO_PARAMETER_FOUND_FOR_SPECIFIED_NAME = "NO_PARAMETER_FOUND_FOR_SPECIFIED_NAME"
	const val COMPARING_WRONG_PARAMETER_TYPE = "COMPARING_WRONG_PARAMETER_TYPE"
	const val NOT_FOUND_WITH_GIVEN_IDENTIFIER = "NOT_FOUND_WITH_GIVEN_IDENTIFIER"
	const val INVALID_TOKEN = "INVALID_TOKEN"
	const val NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
	const val FAILED_TO_LOGIN_FOR_UNKNOWN_REASON = "FAILED_TO_LOGIN_FOR_UNKNOWN_REASON"
	const val NOT_ENOUGH_PERMISSION = "NOT_ENOUGH_PERMISSION"
	const val PARAMETER_TYPE_MISMATCH = "PARAMETER_TYPE_MISMATCH"
	const val DATE_IS_NULL = "DATE_IS_NULL"
	const val TIME_IS_SET_BUT_NOT_DATE = "TIME_IS_SET_BUT_NOT_DATE"
	const val PAGE_SIZE_IS_LOWER_THAN_ONE = "PAGE_SIZE_IS_LOWER_THAN_ONE"
	const val PAGE_SIZE_IS_UPPER_THAN_MAX_PAGE_SIZE = "PAGE_SIZE_IS_UPPER_THAN_MAX_PAGE_SIZE"
	const val PAGE_NUMBER_IS_LOWER_THAN_ZERO = "PAGE_NUMBER_IS_LOWER_THAN_ZERO"
	const val UNKNOWN_ERROR = "UNKNOWN_ERROR"

	object AuthError {
		const val AUTH_EMAIL_OR_ID_NOT_FOUND_IN_TOKEN = "AUTH_EMAIL_OR_ID_NOT_FOUND_IN_TOKEN"
		const val AUTH_BLOCKED_ACCOUNT = "AUTH_BLOCKED_ACCOUNT"
		const val AUTH_IMPERSONATED_ACCOUNT = "AUTH_IMPERSONATED_ACCOUNT"
		const val AUTH_EMAIL_ALREADY_USED = "AUTH_EMAIL_ALREADY_USED"
		const val REDIRECT_URI_BLANK = "REDIRECT_URI_BLANK"
		const val REDIRECT_URI_NOT_ALLOWED = "REDIRECT_URI_NOT_ALLOWED"
		const val AUTHORIZATION_CODE_BLANK = "AUTHORIZATION_CODE_BLANK"
		const val REFRESH_COOKIE_MISSING = "REFRESH_COOKIE_MISSING"
		const val AUTH_PROVIDER_FAILED = "AUTH_PROVIDER_FAILED"
		const val AUTHORIZATION_CODE_OUTDATED = "AUTHORIZATION_CODE_OUTDATED"
		const val REFRESH_TOKEN_OUTDATED = "REFRESH_TOKEN_OUTDATED"
	}

	object UserError {
		const val USER_ASSIGNS_ROLE_HIGHER_THAN_ITS_OWN = "USER_ASSIGNS_ROLE_HIGHER_THAN_ITS_OWN"
		const val USER_UPDATE_LAST_APPLICATION_ADMINISTRATOR_ROLE = "USER_UPDATE_LAST_APPLICATION_ADMINISTRATOR_ROLE"
		const val USER_BLOCK_LAST_APPLICATION_ADMINISTRATOR = "USER_BLOCK_LAST_APPLICATION_ADMINISTRATOR"
		const val USER_BLOCK_LAST_PROJECT_ADMINISTRATOR = "USER_BLOCK_LAST_PROJECT_ADMINISTRATOR"
		const val USER_BLOCK_CURRENT_USER = "USER_BLOCK_CURRENT_USER"
		const val USER_IMPERSONATE_CURRENT_USER = "USER_IMPERSONATE_CURRENT_USER"
		const val USER_DELETE_CURRENT_USER = "USER_DELETE_CURRENT_USER"
		const val USER_IMPERSONATE_LAST_APPLICATION_ADMINISTRATOR = "USER_IMPERSONATE_LAST_APPLICATION_ADMINISTRATOR"
		const val USER_IMPERSONATE_LAST_PROJECT_ADMINISTRATOR = "USER_IMPERSONATE_LAST_PROJECT_ADMINISTRATOR"
		const val USER_DELETE_LAST_APPLICATION_ADMINISTRATOR = "USER_DELETE_LAST_APPLICATION_ADMINISTRATOR"
		const val USER_DELETE_LAST_PROJECT_ADMINISTRATOR = "USER_DELETE_LAST_PROJECT_ADMINISTRATOR"
	}

	object ProjectError {
		const val PROJECT_NAME_NULL_OR_BLANK = "PROJECT_NAME_NULL_OR_BLANK"
		const val PROJECT_NAME_TOO_LONG = "PROJECT_NAME_TOO_LONG"
		const val PROJECT_BEGIN_LATER_THAN_END_TIME = "PROJECT_BEGIN_LATER_THAN_END_TIME"
		const val PROJECT_OPTIONS_MISSING = "PROJECT_OPTIONS_MISSING"
		const val PROJECT_DATE_CONFLICT_WITH_ELEMENTS = "PROJECT_DATE_CONFLICT_WITH_ELEMENTS"
	}

	object ProjectProfileError {
		const val PROJECT_PROFILE_ROLE_BLANK = "PROJECT_PROFILE_ROLE_BLANK"
		const val PROJECT_PROFILE_START_ACCESS_LATER_THAN_END_ACCESS = "PROJECT_START_ACCESS_LATER_THAN_END_ACCESS"
		const val PROJECT_PROFILE_USERS_EMPTY = "PROJECT_PROFILE_USERS_EMPTY"
		const val PROJECT_PROFILE_STATUS_NOT_ACCEPTED_OR_REJECTED = "PROJECT_PROFILE_STATUS_NOT_ACCEPTED_OR_REJECTED"
		const val PROJECT_PROFILE_BLOCK_LAST_PROJECT_ADMINISTRATOR = "PROJECT_PROFILE_BLOCK_LAST_PROJECT_ADMINISTRATOR"
		const val PROJECT_PROFILE_DELETE_LAST_PROJECT_ADMINISTRATOR =
			"PROJECT_PROFILE_DELETE_LAST_PROJECT_ADMINISTRATOR"
		const val PROJECT_PROFILE_UPDATE_LAST_PROJECT_ADMINISTRATOR =
			"PROJECT_PROFILE_UPDATE_LAST_PROJECT_ADMINISTRATOR"
		const val PROJECT_PROFILE_UPDATE_ROLE_HIGHER_THAN_CURRENT_USER =
			"PROJECT_PROFILE_UPDATE_ROLE_HIGHER_THAN_CURRENT_USER"
		const val PROJECT_PROFILE_ASSIGNS_ROLE_HIGHER_THAN_CURRENT_USER =
			"PROJECT_PROFILE_ASSIGNS_ROLE_HIGHER_THAN_CURRENT_USER"
		const val PROJECT_PROFILE_ALREADY_EXIST_ON_RANGE = "PROJECT_PROFILE_ALREADY_EXIST_ON_RANGE"
	}

	object ParticipantError {
		const val PARTICIPANT_FIRST_NAME_NULL_OR_BLANK = "PARTICIPANT_FIRST_NAME_NULL_OR_BLANK"
		const val PARTICIPANT_FIRST_NAME_TOO_LONG = "PARTICIPANT_FIRST_NAME_TOO_LONG"
		const val PARTICIPANT_LAST_NAME_NULL_OR_BLANK = "PARTICIPANT_LAST_NAME_NULL_OR_BLANK"
		const val PARTICIPANT_LAST_NAME_TOO_LONG = "PARTICIPANT_LAST_NAME_TOO_LONG"
		const val PARTICIPANT_BIRTHDAY_NULL = "PARTICIPANT_BIRTHDAY_NULL"
		const val PARTICIPANT_BIRTHDAY_FUTURE = "PARTICIPANT_BIRTHDAY_FUTURE"
		const val PARTICIPANT_START_LATER_THAN_END = "PARTICIPANT_START_LATER_THAN_END"
		const val PARTICIPANT_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE =
			"PARTICIPANT_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE"
		const val PARTICIPANT_IN_PROJECT_ALREADY_LINKED_TO_USER = "PARTICIPANT_IN_PROJECT_ALREADY_LINKED_TO_USER"
		const val PARTICIPANT_OUT_OF_MOVEMENT_DATETIME = "PARTICIPANT_OUT_OF_MOVEMENT_DATETIME"
		const val PARTICIPANT_GROUPS_NOT_FOUND_IN_PARTICIPANT_PROJECT =
			"PARTICIPANT_GROUPS_NOT_FOUND_IN_PARTICIPANT_PROJECT"
		const val PARTICIPANT_GROUPS_NOT_VISIBLE = "PARTICIPANT_GROUPS_NOT_VISIBLE"
		const val PARTICIPANT_DISABLE_LAST_GROUP_MEMBER = "PARTICIPANT_DISABLE_LAST_GROUP_MEMBER"
		const val PARTICIPANT_DELETE_HAS_MOVEMENT = "PARTICIPANT_DELETE_HAS_MOVEMENT"
		const val PARTICIPANT_DELETE_LAST_GROUP_MEMBER = "PARTICIPANT_DELETE_LAST_GROUP_MEMBER"
	}

	object MovementError {
		const val MOVEMENT_DATETIME_NULL = "MOVEMENT_DATETIME_NULL"
		const val MOVEMENT_DATETIME_OUT_OF_PROJECT_DATE_RANGE = "MOVEMENT_DATETIME_OUT_OF_PROJECT_DATE_RANGE"
		const val MOVEMENT_TYPE_NULL = "MOVEMENT_TYPE_NULL"
		const val MOVEMENT_CONTENT_EMPTY = "MOVEMENT_CONTENT_EMPTY"
		const val MOVEMENT_CONTENT_PARTICIPANT_ID_NULL = "MOVEMENT_CONTENT_PARTICIPANT_ID_NULL"
		const val MOVEMENT_ODD_GUEST_CONTENT = "MOVEMENT_ODD_GUEST_CONTENT"
		const val MOVEMENT_REMOVE_GUEST_CONTENT = "MOVEMENT_REMOVE_GUEST_CONTENT"
		const val MOVEMENT_PARTICIPANTS_NOT_FOUND_IN_MOVEMENT_PROJECT =
			"MOVEMENT_PARTICIPANTS_NOT_FOUND_IN_MOVEMENT_PROJECT"
		const val MOVEMENT_PARTICIPANTS_NOT_VISIBLE = "MOVEMENT_PARTICIPANTS_NOT_VISIBLE"
		const val MOVEMENT_DRIVERS_NOT_MAJOR = "MOVEMENT_DRIVERS_NOT_MAJOR"
		const val MOVEMENT_VEHICLES_NOT_FOUND_IN_MOVEMENT_PROJECT = "MOVEMENT_VEHICLES_NOT_FOUND_IN_MOVEMENT_PROJECT"
		const val MOVEMENT_VEHICLES_NOT_VISIBLE = "MOVEMENT_VEHICLES_NOT_VISIBLE"
		const val MOVEMENT_TYPE_AND_REASON_ARE_INCOMPATIBLE = "MOVEMENT_TYPE_AND_REASON_ARE_INCOMPATIBLE"
		const val MOVEMENT_ACTIVITY_AND_REASON_ARE_DEFINED = "MOVEMENT_ACTIVITY_AND_REASON_ARE_DEFINED"
		const val MOVEMENT_ACTIVITY_NOT_FOUND_IN_MOVEMENT_PROJECT = "MOVEMENT_ACTIVITY_NOT_FOUND_IN_MOVEMENT_PROJECT"
		const val MOVEMENT_ACTIVITY_NOT_VISIBLE = "MOVEMENT_ACTIVITY_NOT_VISIBLE"
		const val MOVEMENT_COMMUNICATION_OUT_OF_MOVEMENT_DATETIME = "MOVEMENT_COMMUNICATION_OUT_OF_MOVEMENT_DATETIME"
		const val MOVEMENT_UPDATE_CHANGE_TYPE = "MOVEMENT_UPDATE_CHANGE_TYPE"
		const val MOVEMENT_UPDATE_CHANGE_CONTENT_TYPE = "MOVEMENT_UPDATE_CHANGE_CONTENT_TYPE"
		const val MOVEMENT_CANNOT_BE_UPDATED = "MOVEMENT_CANNOT_BE_UPDATED"
		const val MOVEMENT_CANNOT_BE_DISABLED = "MOVEMENT_CANNOT_BE_DISABLED"
		const val MOVEMENT_CANNOT_BE_ENABLED = "MOVEMENT_CANNOT_BE_ENABLED"
		const val MOVEMENT_CANNOT_BE_DELETED = "MOVEMENT_CANNOT_BE_DELETED"
	}

	object GroupError {
		const val GROUP_NAME_NULL_OR_BLANK = "GROUP_NAME_NULL_OR_BLANK"
		const val GROUP_NAME_TOO_LONG = "GROUP_NAME_TOO_LONG"
		const val GROUP_START_LATER_THAN_END = "GROUP_START_LATER_THAN_END"
		const val GROUP_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE = "GROUP_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE"
		const val GROUP_MEMBERS_EMPTY = "GROUP_MEMBERS_EMPTY"
		const val GROUP_MEMBERS_NOT_FOUND_IN_GROUP_PROJECT = "GROUP_MEMBERS_NOT_FOUND_IN_GROUP_PROJECT"
		const val GROUP_MEMBERS_ALREADY_ADDED = "GROUP_MEMBERS_ALREADY_ADDED"
		const val GROUP_MEMBERS_NOT_VISIBLE = "GROUP_MEMBERS_NOT_VISIBLE"
		const val GROUP_LAST_MEMBERS_CANNOT_BE_REMOVED = "GROUP_LAST_MEMBERS_CANNOT_BE_REMOVED"
	}

	object VehicleError {
		const val VEHICLE_LICENSE_PLATE_NULL_OR_BLANK = "VEHICLE_LICENSE_PLATE_NULL_OR_BLANK"
		const val VEHICLE_LICENSE_PLATE_TOO_LONG = "VEHICLE_LICENSE_PLATE_TOO_LONG"
		const val VEHICLE_BRAND_NULL_OR_BLANK = "VEHICLE_BRAND_NULL_OR_BLANK"
		const val VEHICLE_BRAND_TOO_LONG = "VEHICLE_BRAND_TOO_LONG"
		const val VEHICLE_MODEL_NULL_OR_BLANK = "VEHICLE_MODEL_NULL_OR_BLANK"
		const val VEHICLE_MODEL_TOO_LONG = "VEHICLE_MODEL_TOO_LONG"
		const val VEHICLE_START_LATER_THAN_END = "VEHICLE_START_LATER_THAN_END"
		const val VEHICLE_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE = "VEHICLE_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE"
		const val VEHICLE_DELETE_HAS_MOVEMENT = "VEHICLE_DELETE_HAS_MOVEMENT"
	}

	object ActivityError {
		const val ACTIVITY_NAME_NULL_OR_BLANK = "ACTIVITY_NAME_NULL_OR_BLANK"
		const val ACTIVITY_NAME_TOO_LONG = "ACTIVITY_NAME_TOO_LONG"
		const val ACTIVITY_DESCRIPTION_TOO_LONG = "ACTIVITY_DESCRIPTION_TOO_LONG"
		const val ACTIVITY_DURATION_FORMAT_FAILED = "ACTIVITY_DURATION_FORMAT_FAILED"
		const val ACTIVITY_ALLOWED_PARTICIPANTS_NULL = "ACTIVITY_ALLOWED_PARTICIPANTS_NULL"
		const val ACTIVITY_ALLOWED_PARTICIPANTS_TOO_LOW = "ACTIVITY_ALLOWED_PARTICIPANTS_TOO_LOW"
		const val ACTIVITY_ALLOWED_PARTICIPANTS_MAX_IS_HIGHER_THAN_MIN =
			"ACTIVITY_ALLOWED_PARTICIPANTS_MAX_IS_HIGHER_THAN_MIN"
		const val ACTIVITY_START_LATER_THAN_END = "ACTIVITY_START_LATER_THAN_END"
		const val ACTIVITY_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE =
			"ACTIVITY_PRESENCE_DATES_OUT_OF_PROJECT_DATE_RANGE"
		const val ACTIVITY_DELETE_HAS_MOVEMENT = "ACTIVITY_DELETE_HAS_MOVEMENT"
	}

	object CommunicationError {
		const val COMMUNICATION_DATETIME_NULL = "COMMUNICATION_DATETIME_NULL"
		const val COMMUNICATION_DATETIME_OUT_OF_PROJECT_DATE_RANGE = "COMMUNICATION_DATETIME_OUT_OF_PROJECT_DATE_RANGE"
		const val COMMUNICATION_MOVEMENT_IS_AFTER_COMMUNICATION = "COMMUNICATION_MOVEMENT_IS_AFTER_COMMUNICATION"
		const val COMMUNICATION_MESSAGE_TOO_LONG = "COMMUNICATION_MESSAGE_TOO_LONG"
		const val COMMUNICATION_MOVEMENT_OR_ALERT_NULL = "COMMUNICATION_MOVEMENT_OR_ALERT_NULL"
		const val COMMUNICATION_MOVEMENT_NOT_FOUND_IN_COMMUNICATION_PROJECT =
			"COMMUNICATION_MOVEMENT_NOT_FOUND_IN_COMMUNICATION_PROJECT"
		const val COMMUNICATION_MOVEMENT_NOT_VISIBLE = "COMMUNICATION_MOVEMENT_NOT_VISIBLE"
		const val COMMUNICATION_MOVEMENT_CONTENT_TYPE_NOT_REGISTERED =
			"COMMUNICATION_MOVEMENT_CONTENT_TYPE_NOT_REGISTERED"
		const val COMMUNICATION_MOVEMENT_TYPE_NOT_OUT = "COMMUNICATION_MOVEMENT_TYPE_NOT_OUT"
		const val COMMUNICATION_ALERT_IS_AFTER_COMMUNICATION = "COMMUNICATION_ALERT_IS_AFTER_COMMUNICATION"
		const val COMMUNICATION_ALERT_IS_NOT_COMPATIBLE_WITH_COMMUNICATION_CREATION =
			"COMMUNICATION_ALERT_IS_NOT_COMPATIBLE_WITH_COMMUNICATION_CREATION"
		const val COMMUNICATION_ALERT_NOT_FOUND_IN_COMMUNICATION_PROJECT =
			"COMMUNICATION_ALERT_NOT_FOUND_IN_COMMUNICATION_PROJECT"
		const val COMMUNICATION_ALERT_NOT_VISIBLE = "COMMUNICATION_ALERT_NOT_VISIBLE"
	}

	object AlertError {
		const val ALERT_TITLE_NULL_OR_BLANK = "ALERT_TITLE_NULL_OR_BLANK"
		const val ALERT_TITLE_TOO_LONG = "ALERT_TITLE_TOO_LONG"
		const val ALERT_STATUS_NULL = "ALERT_STATUS_NULL"
		const val ALERT_DATETIME_OUT_OF_PROJECT_DATE_RANGE = "ALERT_DATETIME_OUT_OF_PROJECT_DATE_RANGE"
		const val ALERT_COMMUNICATION_OUT_OF_ALERT_DATETIME = "ALERT_COMMUNICATION_OUT_OF_ALERT_DATETIME"
		const val ALERT_DELETE_HAS_COMMUNICATION = "ALERT_DELETE_HAS_COMMUNICATION"
		const val ALERT_STATUS_IS_NOT_UPDATABLE = "ALERT_STATUS_IS_NOT_UPDATABLE"
	}

	object PurgeError {
		const val PURGE_DATE_THRESHOLD_IN_FUTURE = "PURGE_DATE_THRESHOLD_IN_FUTURE"
	}
}
