package fr.laucoin.registry.backend.domain.constant

object ErrorConst {
    const val NOT_IMPLEMENTED_YET = "NOT_IMPLEMENTED_YET"
    const val NO_PARAMETER_FOUND_FOR_SPECIFIED_NAME = "NO_PARAMETER_FOUND_FOR_SPECIFIED_NAME"
    const val COMPARING_WRONG_PARAMETER_TYPE = "COMPARING_WRONG_PARAMETER_TYPE"
    const val NOT_FOUND_WITH_GIVEN_IDENTIFIER = "NOT_FOUND_WITH_GIVEN_IDENTIFIER"
    const val NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    const val NOT_ENOUGH_PERMISSION = "NOT_ENOUGH_PERMISSION"
    const val PARAMETER_TYPE_MISMATCH = "PARAMETER_TYPE_MISMATCH"
    const val NOT_ACCEPTED_LANGUAGE_HEADER = "NOT_ACCEPTED_LANGUAGE_HEADER"
    const val UNKNOWN_ERROR = "UNKNOWN_ERROR"

    object AuthError {
        const val AUTH_EMAIL_OR_ID_NOT_FOUND_IN_TOKEN = "AUTH_EMAIL_OR_ID_NOT_FOUND_IN_TOKEN"
        const val AUTH_BLOCKED_ACCOUNT = "AUTH_DISABLED_ACCOUNT"
        const val AUTH_IMPERSONATED_ACCOUNT = "AUTH_IMPERSONATED_ACCOUNT"
        const val REDIRECT_URI_BLANK = "REDIRECT_URI_BLANK"
        const val AUTHORIZATION_CODE_BLANK = "AUTHORIZATION_CODE_BLANK"
        const val REFRESH_TOKEN_BLANK = "REFRESH_TOKEN_BLANK"
        const val AUTH_PROVIDER_FAILED = "AUTH_PROVIDER_FAILED"
        const val AUTHORIZATION_CODE_OUTDATED = "AUTHORIZATION_CODE_OUTDATED"
        const val REFRESH_TOKEN_OUTDATED = "REFRESH_TOKEN_OUTDATED"
    }

    object UserError {
        const val USER_ASSIGNS_ROLE_HIGHER_THAN_ITS_OWN = "USER_ASSIGNS_ROLE_HIGHER_THAN_ITS_OWN"
        const val USER_UPDATE_LAST_APPLICATION_ADMINISTRATOR_ROLE = "USER_UPDATE_LAST_APPLICATION_ADMINISTRATOR_ROLE"
        const val USER_BLOCK_LAST_APPLICATION_ADMINISTRATOR = "USER_BLOCK_LAST_APPLICATION_ADMINISTRATOR"
        const val USER_BLOCK_LAST_EVENT_ADMINISTRATOR = "USER_BLOCK_LAST_EVENT_ADMINISTRATOR"
        const val USER_IMPERSONATE_LAST_APPLICATION_ADMINISTRATOR = "USER_IMPERSONATE_LAST_APPLICATION_ADMINISTRATOR"
        const val USER_IMPERSONATE_LAST_EVENT_ADMINISTRATOR = "USER_IMPERSONATE_LAST_EVENT_ADMINISTRATOR"
        const val USER_DELETE_LAST_APPLICATION_ADMINISTRATOR = "USER_DELETE_LAST_APPLICATION_ADMINISTRATOR"
        const val USER_DELETE_LAST_EVENT_ADMINISTRATOR = "USER_DELETE_LAST_EVENT_ADMINISTRATOR"
    }

    object EventError {
        const val EVENT_NAME_BLANK = "EVENT_NAME_BLANK"
        const val EVENT_NAME_TOO_LONG = "EVENT_NAME_TOO_LONG"
        const val EVENT_BEGIN_LATER_THAN_END_TIME = "EVENT_BEGIN_LATER_THAN_END_TIME"
        const val EVENT_OPTIONS_MISSING = "EVENT_OPTIONS_MISSING"
        const val EVENT_DATE_CONFLICT_WITH_ELEMENTS = "EVENT_DATE_CONFLICT_WITH_ELEMENTS"
    }

    object EventProfileError {
        const val EVENT_PROFILE_ROLE_BLANK = "EVENT_PROFILE_ROLE_BLANK"
        const val EVENT_PROFILE_START_ACCESS_LATER_THAN_END_ACCESS = "EVENT_START_ACCESS_LATER_THAN_END_ACCESS"
        const val EVENT_PROFILE_USERS_EMPTY = "EVENT_PROFILE_USERS_EMPTY"
        const val EVENT_PROFILE_STATUS_NOT_ACCEPTED_OR_REJECTED = "EVENT_PROFILE_STATUS_NOT_ACCEPTED_OR_REJECTED"
        const val EVENT_PROFILE_DELETE_LAST_EVENT_ADMINISTRATOR = "EVENT_PROFILE_DELETE_LAST_EVENT_ADMINISTRATOR"
        const val EVENT_PROFILE_UPDATE_LAST_EVENT_ADMINISTRATOR = "EVENT_PROFILE_UPDATE_LAST_EVENT_ADMINISTRATOR"
        const val EVENT_PROFILE_UPDATE_ROLE_HIGHER_THAN_CURRENT_USER = "EVENT_PROFILE_UPDATE_ROLE_HIGHER_THAN_CURRENT_USER"
        const val EVENT_PROFILE_ASSIGNS_ROLE_HIGHER_THAN_CURRENT_USER = "EVENT_PROFILE_ASSIGNS_ROLE_HIGHER_THAN_CURRENT_USER"
        const val EVENT_PROFILE_ALREADY_EXIST_ON_RANGE = "EVENT_PROFILE_ALREADY_EXIST_ON_RANGE"
    }

    object MovementError {
        const val MOVEMENT_PARTICIPANT_NULL = "MOVEMENT_PARTICIPANT_NULL"
        const val MOVEMENT_DATETIME_NULL = "MOVEMENT_DATETIME_NULL"
        const val MOVEMENT_DATETIME_OUT_OF_EVENT_DATE_RANGE = "MOVEMENT_DATETIME_OUT_OF_EVENT_DATE_RANGE"
        const val MOVEMENT_TYPE_NULL = "MOVEMENT_TYPE_NULL"
        const val MOVEMENT_CONTENT_EMPTY = "MOVEMENT_CONTENT_EMPTY"
        const val MOVEMENT_PARTICIPANTS_NOT_FOUND_IN_MOVEMENT_EVENT = "MOVEMENT_PARTICIPANTS_NOT_FOUND_IN_MOVEMENT_EVENT"
        const val MOVEMENT_PARTICIPANTS_NOT_VISIBLE = "MOVEMENT_PARTICIPANTS_NOT_VISIBLE"
    }

    object ParticipantError {
        const val PARTICIPANT_FIRST_NAME_BLANK = "PARTICIPANT_FIRST_NAME_BLANK"
        const val PARTICIPANT_FIRST_NAME_TOO_LONG = "PARTICIPANT_FIRST_NAME_TOO_LONG"
        const val PARTICIPANT_LAST_NAME_BLANK = "PARTICIPANT_LAST_NAME_BLANK"
        const val PARTICIPANT_LAST_NAME_TOO_LONG = "PARTICIPANT_LAST_NAME_TOO_LONG"
        const val PARTICIPANT_BIRTHDAY_FUTURE = "PARTICIPANT_BIRTHDAY_FUTURE"
        const val PARTICIPANT_START_LATER_THAN_END = "PARTICIPANT_START_LATER_THAN_END"
        const val PARTICIPANT_PRESENCE_DATES_OUT_OF_EVENT_DATE_RANGE = "PARTICIPANT_PRESENCE_DATES_OUT_OF_EVENT_DATE_RANGE"
        const val PARTICIPANT_IN_EVENT_ALREADY_LINKED_TO_USER = "PARTICIPANT_IN_EVENT_ALREADY_LINKED_TO_USER"
        const val PARTICIPANT_GROUPS_NOT_FOUND_IN_PARTICIPANT_EVENT = "PARTICIPANT_GROUPS_NOT_FOUND_IN_PARTICIPANT_EVENT"
        const val PARTICIPANT_GROUPS_NOT_VISIBLE = "PARTICIPANT_GROUPS_NOT_VISIBLE"
    }

    object GroupError {
        const val GROUP_PARTICIPANT_NULL = "GROUP_PARTICIPANT_NULL"
        const val GROUP_NAME_BLANK = "GROUP_NAME_BLANK"
        const val GROUP_NAME_TOO_LONG = "GROUP_NAME_TOO_LONG"
        const val GROUP_START_LATER_THAN_END = "GROUP_START_LATER_THAN_END"
        const val GROUP_PRESENCE_DATES_OUT_OF_EVENT_DATE_RANGE = "GROUP_PRESENCE_DATES_OUT_OF_EVENT_DATE_RANGE"
        const val GROUP_MEMBERS_EMPTY = "GROUP_MEMBERS_EMPTY"
        const val GROUP_MEMBERS_NOT_FOUND_IN_GROUP_EVENT = "GROUP_MEMBERS_NOT_FOUND_IN_GROUP_EVENT"
        const val GROUP_MEMBERS_ALREADY_ADDED = "GROUP_MEMBERS_ALREADY_ADDED"
        const val GROUP_MEMBERS_NOT_VISIBLE = "GROUP_MEMBERS_NOT_VISIBLE"
        const val GROUP_LAST_MEMBERS_CANNOT_BE_REMOVED = "GROUP_LAST_MEMBERS_CANNOT_BE_REMOVED"
    }
}
