package fr.laucoin.registry.backend.domain.constant

object ErrorConst {
    const val NOT_IMPLEMENTED_YET = "NOT_IMPLEMENTED_YET"
    const val NO_PARAMETER_FOUND_FOR_SPECIFIED_NAME = "NO_PARAMETER_FOUND_FOR_SPECIFIED_NAME"
    const val COMPARING_WRONG_PARAMETER_TYPE = "COMPARING_WRONG_PARAMETER_TYPE"
    const val NOT_FOUND_WITH_GIVEN_IDENTIFIER = "NOT_FOUND_WITH_GIVEN_IDENTIFIER"
    const val NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    const val NOT_ENOUGH_PERMISSION = "NOT_ENOUGH_PERMISSION"
    const val PARAMETER_TYPE_MISMATCH = "PARAMETER_TYPE_MISMATCH"
    const val WRONG_AUTHENTICATION_MOD = "WRONG_AUTHENTICATION_MOD"
    const val UNKNOWN_ERROR = "UNKNOWN_ERROR"

    object AuthError {
        const val AUTH_EMAIL_OR_ID_NOT_FOUND_IN_TOKEN = "AUTH_EMAIL_OR_ID_NOT_FOUND_IN_TOKEN"
        const val AUTH_BLOCKED_ACCOUNT = "AUTH_DISABLED_ACCOUNT"
        const val AUTH_IMPERSONATED_ACCOUNT = "AUTH_IMPERSONATED_ACCOUNT"
    }

    object UserError {
        const val USER_ASSIGNS_ROLE_HIGHER_THAN_ITS_OWN = "USER_ASSIGNS_ROLE_HIGHER_THAN_ITS_OWN"
        const val USER_UPDATE_LAST_APPLICATION_ADMINISTRATOR_ROLE = "USER_UPDATE_LAST_APPLICATION_ADMINISTRATOR_ROLE"
        const val USER_BLOCK_LAST_APPLICATION_ADMINISTRATOR = "USER_BLOCK_LAST_APPLICATION_ADMINISTRATOR"
        const val USER_BLOCK_LAST_EVENT_ADMINISTRATOR = "USER_BLOCK_LAST_EVENT_ADMINISTRATOR"
        const val USER_IMPERSONATE_LAST_APPLICATION_ADMINISTRATOR = "USER_IMPERSONATE_LAST_APPLICATION_ADMINISTRATOR"
        const val USER_IMPERSONATE_LAST_EVENT_ADMINISTRATOR = "USER_IMPERSONATE_LAST_EVENT_ADMINISTRATOR"
        const val USER_DELETE_LAST_APPLICATION_ADMINISTRATOR = "USER_DELETE_LAST_APPLICATION_ADMINISTRATOR"
        const val USER_DELETE_LAST_EVENT_ADMINISTRATOR = "USER_DELETE_LAST_EVENT_ADMINISTRATOR"
    }

    object EventError {
        const val EVENT_NAME_BLANK = "EVENT_NAME_BLANK"
        const val EVENT_NAME_TOO_LONG = "EVENT_NAME_TOO_LONG"
        const val EVENT_BEGIN_LATER_THAN_END_TIME = "EVENT_BEGIN_LATER_THAN_END_TIME"
        const val EVENT_OPTIONS_MISSING = "EVENT_OPTIONS_MISSING"
        const val EVENT_DATE_CONFLICT_WITH_ELEMENTS = "EVENT_DATE_CONFLICT_WITH_ELEMENTS"
    }

    object EventProfileError {
        const val EVENT_PROFILE_ROLE_BLANK = "EVENT_PROFILE_ROLE_BLANK"
        const val EVENT_PROFILE_START_ACCESS_LATER_THAN_END_ACCESS = "EVENT_START_ACCESS_LATER_THAN_END_ACCESS"
        const val EVENT_PROFILE_USERS_EMPTY = "EVENT_PROFILE_USERS_EMPTY"
        const val EVENT_PROFILE_STATUS_NOT_ACCEPTED_OR_REJECTED = "EVENT_PROFILE_STATUS_NOT_ACCEPTED_OR_REJECTED"
        const val EVENT_PROFILE_DELETE_LAST_EVENT_ADMINISTRATOR = "EVENT_PROFILE_DELETE_LAST_EVENT_ADMINISTRATOR"
        const val EVENT_PROFILE_UPDATE_LAST_EVENT_ADMINISTRATOR = "EVENT_PROFILE_UPDATE_LAST_EVENT_ADMINISTRATOR"
        const val EVENT_PROFILE_UPDATE_ROLE_HIGHER_THAN_CURRENT_USER = "EVENT_PROFILE_UPDATE_ROLE_HIGHER_THAN_CURRENT_USER"
        const val EVENT_PROFILE_ASSIGNS_ROLE_HIGHER_THAN_CURRENT_USER = "EVENT_PROFILE_ASSIGNS_ROLE_HIGHER_THAN_CURRENT_USER"
        const val EVENT_PROFILE_ALREADY_EXIST_ON_RANGE = "EVENT_PROFILE_ALREADY_EXIST_ON_RANGE"
    }

    object MovementError {
        const val MOVEMENT_PARTICIPANT_NULL = "MOVEMENT_PARTICIPANT_NULL"
        const val MOVEMENT_DATETIME_NULL = "MOVEMENT_DATETIME_NULL"
        const val MOVEMENT_DATETIME_OUT_OF_EVENT_DATE_RANGE = "MOVEMENT_DATETIME_OUT_OF_EVENT_DATE_RANGE"
        const val MOVEMENT_TYPE_NULL = "MOVEMENT_TYPE_NULL"
        const val MOVEMENT_CONTENT_EMPTY = "MOVEMENT_CONTENT_EMPTY"
    }

    object ParticipantError {
        const val PARTICIPANT_FIRST_NAME_BLANK = "PARTICIPANT_FIRST_NAME_BLANK"
        const val PARTICIPANT_FIRST_NAME_TOO_LONG = "PARTICIPANT_FIRST_NAME_TOO_LONG"
        const val PARTICIPANT_LAST_NAME_BLANK = "PARTICIPANT_LAST_NAME_BLANK"
        const val PARTICIPANT_LAST_NAME_TOO_LONG = "PARTICIPANT_LAST_NAME_TOO_LONG"
        const val PARTICIPANT_BIRTHDAY_FUTURE = "PARTICIPANT_BIRTHDAY_FUTURE"
        const val PARTICIPANT_START_LATER_THAN_END = "PARTICIPANT_START_LATER_THAN_END"
        const val PARTICIPANT_PRESENCE_DATES_OUT_OF_EVENT_DATE_RANGE = "PARTICIPANT_PRESENCE_DATES_OUT_OF_EVENT_DATE_RANGE"
        const val PARTICIPANT_IN_EVENT_ALREADY_LINKED_TO_USER = "PARTICIPANT_IN_EVENT_ALREADY_LINKED_TO_USER"
    }
}
