registry:
  information:
    organization: "SGDF"
    name: "SGDF Registry"
    description: "This application allows virtual registry management. This is a backend which one is called by the frontend."
    support:
      name: Luc AUCOIN
      email: laucoin@sgdf.fr
      url: https://sgdf.fr
  security:
    default-role: "USER"
    oauth2:
      base-url: ${external.keycloak.base-url}
      realm: ${external.keycloak.realm}
      client-id: ${external.keycloak.swagger.client-id}
      client-secret: ${external.keycloak.swagger.client-secret}
      claims:
        user-id: "sub"
        email: "email"
        first-name: "given_name"
        last-name: "family_name"
