registry:
  information:
    organization: "SGDF"
    name: "SGDF Registry"
    description: "This application allows virtual registry management. This is a backend which one is called by the frontend."
    support:
      name: Luc AUCOIN
      email: laucoin@sgdf.fr
      url: https://sgdf.fr
  security:
    default-role: "USER"
    oauth2:
      claims:
        user-id: "sub"
        email: "email"
        first-name: "given_name"
        last-name: "family_name"
