logging:
  level:
    fr.laucoin.registry.backend: ${registry.server.logging-level}
    org.springframework.r2dbc: ${registry.server.logging-level}
    org.springframework.web: ${registry.server.logging-level}
    org.springframework.security.oauth2: ${registry.server.logging-level}
    org.springframework.security.oauth2.client: ${registry.server.logging-level}

server:
  port: ${registry.server.port}

registry:
  information:
    name: Registry
    description: This application allows virtual registry management. This is a backend which one is called by the frontend.
    locale:
      default: en-US
      supported: en-US, fr-FR
    support:
      name: Luc AUCOIN
      email: luc.aucoin1998@gmail.com
      url: https://laucoin.fr
  feature:
    profile:
      searched:
        max-user-result: 10
    participant:
      searched:
        max-user-result: 10
        max-group-result: 10
    group:
      searched:
        max-participant-result: 10
    movement:
      searched:
        max-participant-result: 10
        max-group-result: 10
        max-vehicle-result: 10
  security:
    default-role: USER
    oauth2:
      base-url: ${external.keycloak.base-url}
      realm: ${external.keycloak.realm}
      client-id: ${external.keycloak.swagger.client-id}
      client-secret: ${external.keycloak.swagger.client-secret}
      url: ${registry.security.oauth2.base-url}/realms/${registry.security.oauth2.realm}/protocol/openid-connect
      claims:
        user-id: sub
        email: email
        first-name: given_name
        last-name: family_name
  server:
    prefix: /api

spring:
  application:
    name: ${registry.information.name}
  flyway:
    schemas: ${registry.datasource.schemas}
    url: jdbc:postgresql://${registry.datasource.base-url}/${registry.datasource.database}
    user: ${registry.datasource.username}
    password: ${registry.datasource.password}
    locations:
      - classpath:db/migrations
  main:
    web-application-type: reactive
    banner-mode: off
  r2dbc:
    url: r2dbc:pool:postgresql://${registry.datasource.base-url}/${registry.datasource.database}?currentSchema=${registry.datasource.schemas}
    username: ${registry.datasource.username}
    password: ${registry.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${registry.security.oauth2.url}/certs

springdoc:
  api-docs:
    path: /api-docs
    enabled: ${registry.feature.documentation.enabled:false}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${registry.feature.documentation.enabled:false}
    oauth:
      client-id: ${registry.security.oauth2.client-id}
      client-secret: ${registry.security.oauth2.client-secret}
