-- tb_user update service user
UPDATE tb_user
SET first_name = 'Luc',
    last_name  = 'AUCOIN',
    email      = 'luc.aucoin1998@gmail.com'
WHERE type = 'SERVICE_ACCOUNT';

-- tb_user_role insert service user
INSERT INTO tb_user_role(name, level)
VALUES ('USER_ADMINISTRATOR', 0),
       ('USER', 9000);

-- tb_user_role_permission insert service user
INSERT INTO tb_user_role_permission(role, permission)
VALUES ('USER_ADMINISTRATOR', 'REGISTRY_USER_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_USER_METADATA_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_USER_U'),
       ('USER_ADMINISTRATOR', 'REGISTRY_USER_D'),
       ('USER_ADMINISTRATOR', 'REGISTRY_EVENT_METADATA_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_EVENT_C'),
       ('USER_ADMINISTRATOR', 'REGISTRY_EVENT_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_PROFILE_C'),
       ('USER', 'REGISTRY_EVENT_C'),
       ('USER', 'REGISTRY_EVENT_METADATA_R')
;

-- tb_event_role insert service user
INSERT INTO tb_event_role(name, level)
VALUES ('EVENT_ADMINISTRATOR', 0),
       ('EVENT_COORDINATOR', 10),
       ('EVENT_PARTICIPANT', 20);

-- tb_event_role_permission insert service user
INSERT INTO tb_event_role_permission(role, permission)
VALUES ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_D'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PROFILE_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PROFILE_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PROFILE_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PROFILE_D'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PROFILE_METADATA_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PARTICIPANT_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PARTICIPANT_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PARTICIPANT_HISTORY_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PARTICIPANT_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PARTICIPANT_D'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_PARTICIPANT_METADATA_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_D'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_METADATA_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_HISTORY_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_D'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_MOVEMENT_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_MOVEMENT_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_MOVEMENT_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_MOVEMENT_D'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_MOVEMENT_METADATA_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_PROFILE_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_PARTICIPANT_C'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_PARTICIPANT_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_PARTICIPANT_HISTORY_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_PARTICIPANT_U'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_PARTICIPANT_D'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_PARTICIPANT_METADATA_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_C'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_U'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_D'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_METADATA_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_C'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_HISTORY_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_U'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_D'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_MOVEMENT_C'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_MOVEMENT_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_MOVEMENT_U'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_MOVEMENT_D'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_MOVEMENT_METADATA_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_PARTICIPANT_C'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_PARTICIPANT_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_PARTICIPANT_U'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_PARTICIPANT_METADATA_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_C'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_U'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_METADATA_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_MOVEMENT_C'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_MOVEMENT_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_MOVEMENT_U'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_MOVEMENT_METADATA_R')
;
