-- tb_user insert service user
INSERT INTO tb_user(type, first_name, last_name, email)
VALUES ('SERVICE_ACCOUNT', 'Luc', 'AUCOIN', 'luc.aucoin1998@gmail.com');

-- tb_user_permission insert user permissions
INSERT INTO tb_user_permission(name)
VALUES ('REGISTRY_USER_R'),
       ('REGISTRY_USER_U'),
       ('REGISTRY_USER_D'),
       ('REGISTRY_USER_METADATA_R'),
       ('REGISTRY_PROJECT_C'),
       ('REGISTRY_PROJECT_R'),
       ('REGISTRY_PROJECT_METADATA_R'),
       ('REGISTRY_PROFILE_C')
;

-- tb_project_permission insert project permissions
INSERT INTO tb_project_permission(name)
VALUES ('REGISTRY_PROJECT_R'),
       ('REGISTRY_PROJECT_U'),
       ('REGISTRY_PROJECT_D'),
       ('REGISTRY_PROJECT_PROFILE_C'),
       ('REGISTRY_PROJECT_PROFILE_R'),
       ('REGISTRY_PROJECT_PROFILE_U'),
       ('REGISTRY_PROJECT_PROFILE_D'),
       ('REGISTRY_PROJECT_PROFILE_METADATA_R'),
       ('REGISTRY_PROJECT_PARTICIPANT_C'),
       ('REGISTRY_PROJECT_PARTICIPANT_R'),
       ('REGISTRY_PROJECT_PARTICIPANT_HISTORY_R'),
       ('REGISTRY_PROJECT_PARTICIPANT_U'),
       ('REGISTRY_PROJECT_PARTICIPANT_D'),
       ('REGISTRY_PROJECT_PARTICIPANT_METADATA_R'),
       ('REGISTRY_PROJECT_MOVEMENT_C'),
       ('REGISTRY_PROJECT_MOVEMENT_R'),
       ('REGISTRY_PROJECT_MOVEMENT_U'),
       ('REGISTRY_PROJECT_MOVEMENT_D'),
       ('REGISTRY_PROJECT_MOVEMENT_METADATA_R')
;

-- tb_user_role insert user roles
INSERT INTO tb_user_role(name, level)
VALUES ('USER_ADMINISTRATOR', 0),
       ('USER', 9000);

-- tb_project_role_permission insert user basic role/permission mapping
INSERT INTO tb_user_role_permission(role, permission)
VALUES ('USER_ADMINISTRATOR', 'REGISTRY_USER_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_USER_METADATA_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_USER_U'),
       ('USER_ADMINISTRATOR', 'REGISTRY_USER_D'),
       ('USER_ADMINISTRATOR', 'REGISTRY_PROJECT_METADATA_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_PROJECT_C'),
       ('USER_ADMINISTRATOR', 'REGISTRY_PROJECT_R'),
       ('USER_ADMINISTRATOR', 'REGISTRY_PROFILE_C'),
       ('USER', 'REGISTRY_PROJECT_C'),
       ('USER', 'REGISTRY_PROJECT_METADATA_R')
;

-- tb_project_role insert project roles
INSERT INTO tb_project_role(name, level)
VALUES ('PROJECT_ADMINISTRATOR', 0),
       ('PROJECT_COORDINATOR', 10),
       ('PROJECT_PARTICIPANT', 20);

-- tb_project_role_permission insert project basic role/permission mapping
INSERT INTO tb_project_role_permission(role, permission)
VALUES ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_D'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PROFILE_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PROFILE_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PROFILE_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PROFILE_D'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PROFILE_METADATA_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PARTICIPANT_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PARTICIPANT_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PARTICIPANT_HISTORY_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PARTICIPANT_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PARTICIPANT_D'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_PARTICIPANT_METADATA_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_MOVEMENT_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_MOVEMENT_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_MOVEMENT_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_MOVEMENT_D'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_MOVEMENT_METADATA_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_PROFILE_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_PARTICIPANT_C'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_PARTICIPANT_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_PARTICIPANT_HISTORY_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_PARTICIPANT_U'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_PARTICIPANT_METADATA_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_MOVEMENT_C'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_MOVEMENT_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_MOVEMENT_U'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_MOVEMENT_D'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_MOVEMENT_METADATA_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_PARTICIPANT_C'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_PARTICIPANT_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_PARTICIPANT_U'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_PARTICIPANT_METADATA_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_MOVEMENT_C'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_MOVEMENT_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_MOVEMENT_U'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_MOVEMENT_METADATA_R')
;
