-- tb_event_permission insert group in event permissions
INSERT INTO tb_event_permission(name)
VALUES ('REGISTRY_EVENT_GROUP_C'),
       ('REGISTRY_EVENT_GROUP_R'),
       ('REGISTRY_EVENT_GROUP_U'),
       ('REGISTRY_EVENT_GROUP_D'),
       ('REGISTRY_EVENT_GROUP_METADATA_R')
;

-- tb_event_role_permission insert group in event role/permission mapping
INSERT INTO tb_event_role_permission(role, permission)
VALUES ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_D'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_GROUP_METADATA_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_C'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_U'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_GROUP_METADATA_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_C'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_R'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_U'),
       ('EVENT_PARTICIPANT', 'REGISTRY_EVENT_GROUP_METADATA_R')
;
