-- tb_project_permission insert group in project permissions
INSERT INTO tb_project_permission(name)
VALUES ('REGISTRY_PROJECT_GROUP_C'),
       ('REGISTRY_PROJECT_GROUP_R'),
       ('REGISTRY_PROJECT_GROUP_U'),
       ('REGISTRY_PROJECT_GROUP_D'),
       ('REGISTRY_PROJECT_GROUP_METADATA_R')
;

-- tb_project_role_permission insert group in project role/permission mapping
INSERT INTO tb_project_role_permission(role, permission)
VALUES ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_GROUP_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_GROUP_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_GROUP_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_GROUP_D'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_GROUP_METADATA_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_GROUP_C'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_GROUP_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_GROUP_U'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_GROUP_METADATA_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_GROUP_C'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_GROUP_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_GROUP_U'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_GROUP_METADATA_R')
;
