-- tb_event_permission insert vehicle in event permissions
INSERT INTO tb_event_permission(name)
VALUES ('REGISTRY_EVENT_VEHICLE_C'),
       ('REGISTRY_EVENT_VEHICLE_R'),
       ('REGISTRY_EVENT_VEHICLE_HISTORY_R'),
       ('REGISTRY_EVENT_VEHICLE_U'),
       ('REGISTRY_EVENT_VEHICLE_D')
;

-- tb_event_role_permission insert vehicle in event role/permission mapping
INSERT INTO tb_event_role_permission(role, permission)
VALUES ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_HISTORY_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_VEHICLE_D'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_C'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_HISTORY_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_VEHICLE_U')
;
