-- tb_project_permission insert vehicle in project permissions
INSERT INTO tb_project_permission(name)
VALUES ('REGISTRY_PROJECT_VEHICLE_C'),
       ('REGISTRY_PROJECT_VEHICLE_R'),
       ('REGISTRY_PROJECT_VEHICLE_HISTORY_R'),
       ('REGISTRY_PROJECT_VEHICLE_U'),
       ('REGISTRY_PROJECT_VEHICLE_D')
;

-- tb_project_role_permission insert vehicle in project role/permission mapping
INSERT INTO tb_project_role_permission(role, permission)
VALUES ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_VEHICLE_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_VEHICLE_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_VEHICLE_HISTORY_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_VEHICLE_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_VEHICLE_D'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_VEHICLE_C'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_VEHICLE_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_VEHICLE_HISTORY_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_VEHICLE_U')
;
