-- tb_event_permission insert activity in event permissions
INSERT INTO tb_event_permission(name)
VALUES ('REGISTRY_EVENT_ACTIVITY_C'),
       ('REGISTRY_EVENT_ACTIVITY_R'),
       ('REGISTRY_EVENT_ACTIVITY_HISTORY_R'),
       ('REGISTRY_EVENT_ACTIVITY_U'),
       ('REGISTRY_EVENT_ACTIVITY_D')
;

-- tb_event_role_permission insert activity in event role/permission mapping
INSERT INTO tb_event_role_permission(role, permission)
VALUES ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_ACTIVITY_C'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_ACTIVITY_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_ACTIVITY_HISTORY_R'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_ACTIVITY_U'),
       ('EVENT_ADMINISTRATOR', 'REGISTRY_EVENT_ACTIVITY_D'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_ACTIVITY_C'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_ACTIVITY_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_ACTIVITY_HISTORY_R'),
       ('EVENT_COORDINATOR', 'REGISTRY_EVENT_ACTIVITY_U')
;
