-- tb_project_permission insert activity in project permissions
INSERT INTO tb_project_permission(name)
VALUES ('REGISTRY_PROJECT_ACTIVITY_C'),
       ('REGISTRY_PROJECT_ACTIVITY_R'),
       ('REGISTRY_PROJECT_ACTIVITY_HISTORY_R'),
       ('REGISTRY_PROJECT_ACTIVITY_U'),
       ('REGISTRY_PROJECT_ACTIVITY_D')
;

-- tb_project_role_permission insert activity in project role/permission mapping
INSERT INTO tb_project_role_permission(role, permission)
VALUES ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ACTIVITY_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ACTIVITY_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ACTIVITY_HISTORY_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ACTIVITY_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ACTIVITY_D'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ACTIVITY_C'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ACTIVITY_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ACTIVITY_HISTORY_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ACTIVITY_U')
;
