-- tb_project_permission insert communication in project permissions
INSERT INTO tb_project_permission(name)
VALUES ('REGISTRY_PROJECT_COMMUNICATION_C'),
       ('REGISTRY_PROJECT_COMMUNICATION_R'),
       ('REGISTRY_PROJECT_COMMUNICATION_U'),
       ('REGISTRY_PROJECT_COMMUNICATION_D'),
       ('REGISTRY_PROJECT_COMMUNICATION_METADATA_R'),
       ('REGISTRY_PROJECT_MOVEMENT_COMMUNICATION_R')
;

-- tb_project_role_permission insert communication in project role/permission mapping
INSERT INTO tb_project_role_permission(role, permission)
VALUES ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_COMMUNICATION_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_COMMUNICATION_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_COMMUNICATION_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_COMMUNICATION_D'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_COMMUNICATION_METADATA_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_MOVEMENT_COMMUNICATION_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_COMMUNICATION_C'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_COMMUNICATION_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_COMMUNICATION_U'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_COMMUNICATION_METADATA_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_MOVEMENT_COMMUNICATION_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_COMMUNICATION_C'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_COMMUNICATION_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_COMMUNICATION_U'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_COMMUNICATION_METADATA_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_MOVEMENT_COMMUNICATION_R')
;
