-- tb_project_permission insert communication in project permissions
INSERT INTO tb_project_permission(name)
VALUES ('REGISTRY_PROJECT_ALERT_C'),
       ('REGISTRY_PROJECT_ALERT_R'),
       ('REGISTRY_PROJECT_ALERT_U'),
       ('REGISTRY_PROJECT_ALERT_D'),
       ('REGISTRY_PROJECT_ALERT_COMMUNICATION_R')
;

-- tb_project_role_permission insert communication in project role/permission mapping
INSERT INTO tb_project_role_permission(role, permission)
VALUES ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ALERT_C'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ALERT_R'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ALERT_U'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ALERT_D'),
       ('PROJECT_ADMINISTRATOR', 'REGISTRY_PROJECT_ALERT_COMMUNICATION_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ALERT_C'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ALERT_R'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ALERT_U'),
       ('PROJECT_COORDINATOR', 'REGISTRY_PROJECT_ALERT_COMMUNICATION_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_ALERT_C'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_ALERT_R'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_ALERT_U'),
       ('PROJECT_PARTICIPANT', 'REGISTRY_PROJECT_ALERT_COMMUNICATION_R')
;
