services:
  registry-database:
    image: postgres:17-alpine
    platform: linux/amd64
    container_name: registry_database
    networks:
      - registry_network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_MULTIPLE_DATABASES: $DB_REGISTRY,$DB_SSO
    restart: 'unless-stopped'
    volumes:
      - ./postgres/scripts/:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  registry-keycloak:
    image: registry.gitlab.com/laucoin/keycloak-theme:main
    platform: linux/amd64
    container_name: registry_keycloak
    networks:
      - registry_network
    ports:
      - '8080:8080'
    environment:
      KC_DB: 'postgres'
      KC_DB_URL: 'jdbc:postgresql://registry_database:5432/${DB_SSO}'
      KC_DB_USERNAME: $DB_USERNAME
      KC_DB_PASSWORD: $DB_PASSWORD
      KC_DB_SCHEMA: 'public'
      KEYCLOAK_ADMIN: $KC_ADMIN_USERNAME
      KEYCLOAK_ADMIN_PASSWORD: $KC_ADMIN_PASSWORD
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command: start-dev
    restart: 'unless-stopped'
    depends_on:
      registry-database:
        condition: service_healthy

  registry-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: "vscode"
        USER_UID: 1000
        USER_GID: 1000
    container_name: registry-backend
    networks:
      - registry_network
    ports:
      - '8081:8081'
      - '5005:5005'
    environment:
      JAVA_OPTS: >-
        -Dregistry.datasource.schemas=public
        -Dregistry.datasource.base-url=registry_database:5432
        -Dregistry.datasource.database=$DB_REGISTRY
        -Dregistry.datasource.username=$DB_USERNAME
        -Dregistry.datasource.password=$DB_PASSWORD
        -Dexternal.keycloak.base-url=http://localhost:8080
        -Dexternal.keycloak.realm=$KC_REALM
        -Dexternal.keycloak.client-id=$KC_PRIVATE_CLIENT_ID
        -Dexternal.keycloak.client-secret=$KC_PRIVATE_CLIENT_SECRET
        -Dexternal.keycloak.swagger.client-id=$KC_PUBLIC_CLIENT_ID
        -Dregistry.server.logging-level=DEBUG
        -Dregistry.server.port=8081
        -Dregistry.feature.documentation.enabled=true
        -Dexternal.cors.urls=$CORS_URLS
    command: sleep infinity
    restart: 'unless-stopped'
    volumes:
      - .:/workspace:cached
    depends_on:
      registry-database:
        condition: service_healthy

networks:
  registry_network:
    name: registry_network
