package com.laucoin.registry.core.model.util

enum class ErrorEnum {
    OIDC_LOGIN_FAILED,
    FAILED_TO_GET_ID_OR_EMAIL_AT_LOGIN,
    DISABLED_ACCOUNT,
    NOT_IMPLEMENTED_YET,
    START_CANT_BE_LATER_THAN_END,
    CANT_ALTER_SERVICE_ACCOUNT,
    CANT_BLOCK_YOURSELF,
    PROFILE_CONFLICT,
    CANT_ASSIGN_OR_UPDATE_HIGHER_ROLE_PROFILE,
    CANT_ALTER_LAST_USER_MANAGER,
    CANT_ALTER_LAST_EVENT_MANAGER,
    NOT_FOUND_WITH_GIVEN_IDENTIFIER,
    NOT_SELECTABLE_PROFILE
}
